name: Request a feature
description: Use this to request a feature
title: "[Feature request]: "
labels: 
  - "enhancement"
  - "need triage"
body:
- type: checkboxes
  attributes:
    label: Preflight Checklist
    description: Please ensure you've completed all of the following.
    options:
      - label: I have read the [Contributing Guidelines](https://github.com/GeekCornerGH/Threema-For-Desktop/blob/master/CONTRIBUTING.md) for this project.
        required: true
      - label: I have searched the [issue tracker](https://www.github.com/GeekCornerGH/Threema-For-Desktop/issues) for an issue that matches the one I want to file, without success.
        required: true
- type: input
  attributes:
    label: Describe your problem
    description: Explain why you want this feature.
    placeholder: I want this feature because...
  validations:
    required: true
- type: input
  attributes:
    label: Alternatives
    description: What alternatives are avaliable?
    placeholder: 2.1.0
- type: textarea
  attributes:
    label: Additional Information
    description: If we need further explanation, please add more information here.