name: Threema For Desktop CD

on: 
  push:
    tags:
      - 'v*'
jobs: 
  draftrelease:
    name: Make draft for the release
    runs-on: ubuntu-latest
    steps:
      - name: Create the draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  CD:
    name: CD
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: Install and setup Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
      - name: Cloning and checking the repository with Git
        uses: actions/checkout@v2 
      - name: Install dependances to see if there is any issue
        run: yarn --frozen-lockfile
      - name: Run tsc, to check if there is error with code
        run: yarn tsc
      - name: Running build of app
        run: yarn build
        env:
          GH_TOKEN: ${{ secrets.github_token }}
