name: Threema For Desktop CD

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
jobs:
  CD:
    name: CD
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: Install and setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
      - name: Cloning and checking the repository with Git
        uses: actions/checkout@v3
      - name: Inject metadata in npmrc
        run: |
          echo "node-linker=hoisted" >> .npmrc
      - name: Install dependances to see if there is any issue
        run: pnpm install --frozen-lockfile
      - name: Liniting files
        run: pnpm lint:fix
      - name: Building TypeScript to JavaScript
        run: pnpm tsc
      - name: Running build of app
        run: pnpm ciBuild
        env:
          GH_TOKEN: ${{ secrets.github_token }}
      - name: Upload arteficts to Actions log
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-artifacts
          path: |
            build-binaries/**
