name: Threema For Desktop CI

on: 
  push:
    branches-ignore:
      - 'dependabot/**'
      - 'renovate/**'


jobs: 
  CI:
    name: CI
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: Cloning and checking the repository with Git
        uses: actions/checkout@v3
      - name: Install and setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.4.0
        with:
          version: latest
      - name: Inject metadata in npmrc
        run: |
          echo "node-linker=hoisted" >> .npmrc
      - name: Install dependances to see if there is any issue
        run: pnpm install --frozen-lockfile
      - name: Run tsc, to check if there is error with code
        run: pnpm tsc
      - name: Running test build of app
        run: pnpm build
        env:
          GH_TOKEN: ${{ secrets.github_token }}
      - name: Upload artifacts to Actions log
        uses: actions/upload-artifact@v3
        with: 
          name: ${{ runner.os }}-artifacts
          path: |
           build-binaries/**
