name: Threema For Desktop CI for Pull Requests

on: 
  - pull_request


jobs: 
  CIPR:
    name: CI for Pull Requests
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: Cloning and checking the repository with Git
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Install and setup Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
      - name: Install dependances to see if there is any issue
        run: yarn --frozen-lockfile
      - name: Run tsc, to check if there is error with code
        run: yarn tsc
      - name: Running test build of app
        run: yarn build
        env:
          GH_TOKEN: ${{ secrets.github_token }}
      - name: Upload arteficts to Actions log
        uses: actions/upload-artifact@v2 
        with: 
          name: ${{ matrix.os }}-artifacts
          path: | 
            build-binaries/**
