name: Submit Threema For Desktop to winget
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:

  winget:
    name: Publish winget package
    runs-on: windows-latest
    steps:
      - name: Submit package to Windows Package Manager Community Repository
        run: |
          iwr https://github.com/microsoft/winget-create/releases/download/v1.1.2.0/wingetcreate.exe -OutFile wingetcreate.exe
          $github = Get-Content '${{ github.event_path }}' | ConvertFrom-Json
          $installerUrl = $github.release.assets | Where-Object -Property name -match 'Threema-For-Desktop-setup-.*\.exe' | Select -ExpandProperty browser_download_url -First 1
          .\wingetcreate.exe update --urls "https://github.com/GeekCornerGH/threema-for-desktop/releases/download/v2.5.1/Threema-For-Desktop-setup-2.5.1.exe" --version 2.5.1 GeekCorner.threema
          .\wingetcreate.exe update --out manifests --token ${{ secrets.WINGET_PAT }} --version 2.5.1 GeekCorner.threema
