name: 'Threema For Desktop Semantic PR Checker'

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  semantic:
    runs-on: ubuntu-latest
    steps:
      - uses: kunalnagarco/action-semantic-pr@v1.4.10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}